package dev.fivesaw.sawbot.common.events;
public enum ObservationEventType { DAMAGE_RECEIVED, DAMAGE_DEALT, HIT_CONFIRMED, ENTITY_HURT_OBSERVED, ITEM_COLLECTED, ITEM_SPENT, ENTITY_ENTERED_RANGE, ENTITY_LEFT_RANGE, BLOCK_PLACED, BLOCK_BROKEN, SERVER_CORRECTION, RESPAWNED }
